/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ARM-PC
 */
public class form2 extends javax.swing.JFrame {

    /**
     * Creates new form form2
     */
    public form2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFilename = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCreatefile = new javax.swing.JButton();
        btncreateFile = new javax.swing.JButton();
        btnTestInput = new javax.swing.JButton();
        btngetnumber = new javax.swing.JButton();
        btngetIntnumber = new javax.swing.JButton();
        btnRemoveNumber = new javax.swing.JButton();
        btnCreateEmptyFiles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("FileName:");

        btnCreatefile.setText("Create File");
        btnCreatefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatefileActionPerformed(evt);
            }
        });

        btncreateFile.setText("Create CustomFile");
        btncreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateFileActionPerformed(evt);
            }
        });

        btnTestInput.setText("Test InputBox");
        btnTestInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestInputActionPerformed(evt);
            }
        });

        btngetnumber.setText("GetNumber");
        btngetnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetnumberActionPerformed(evt);
            }
        });

        btngetIntnumber.setText("GetIntNumber");
        btngetIntnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetIntnumberActionPerformed(evt);
            }
        });

        btnRemoveNumber.setText("RemoveNumber");
        btnRemoveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveNumberActionPerformed(evt);
            }
        });

        btnCreateEmptyFiles.setText("Create Empty Files");
        btnCreateEmptyFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmptyFilesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFilename, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btngetIntnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btncreateFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreatefile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTestInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btngetnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateEmptyFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreatefile)
                .addGap(18, 18, 18)
                .addComponent(btncreateFile)
                .addGap(18, 18, 18)
                .addComponent(btnTestInput)
                .addGap(18, 18, 18)
                .addComponent(btngetnumber)
                .addGap(18, 18, 18)
                .addComponent(btngetIntnumber)
                .addGap(18, 18, 18)
                .addComponent(btnRemoveNumber)
                .addGap(18, 18, 18)
                .addComponent(btnCreateEmptyFiles)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatefileActionPerformed
        Tools.CreateEmptyFile(txtFilename.getText() + ".txt");
    }//GEN-LAST:event_btnCreatefileActionPerformed

    private void btncreateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateFileActionPerformed
        Object Data[] = {"abdul", 'a', 123, 1.6, true};
        Tools.CreateFile(txtFilename.getText() + ".txt", Data);
    }//GEN-LAST:event_btncreateFileActionPerformed

    private void btnTestInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestInputActionPerformed
        Object obj = Tools.InputBox("Please Enter your Name ");
        Tools.msgBox("Welcome" + " : " + obj);
    }//GEN-LAST:event_btnTestInputActionPerformed

    private void btngetnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetnumberActionPerformed
        Tools.msgBox(Tools.GetNumber("111hfdsaf559876325"));

    }//GEN-LAST:event_btngetnumberActionPerformed

    private void btngetIntnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetIntnumberActionPerformed
        int num = Tools.GetIntNumber("1adsgsdg2");
        Tools.msgBox(String.valueOf(num));
    }//GEN-LAST:event_btngetIntnumberActionPerformed

    private void btnRemoveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveNumberActionPerformed
        Tools.msgBox(Tools.RemoveNumber("111hfdsaf559876325"));
    }//GEN-LAST:event_btnRemoveNumberActionPerformed

    private void btnCreateEmptyFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmptyFilesActionPerformed
        String file1[]={"abdul1" ,"abdul2","abdul3","abdul4"};
        Tools.CreateEmptyFile(file1);
    }//GEN-LAST:event_btnCreateEmptyFilesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEmptyFiles;
    private javax.swing.JButton btnCreatefile;
    private javax.swing.JButton btnRemoveNumber;
    private javax.swing.JButton btnTestInput;
    private javax.swing.JButton btncreateFile;
    private javax.swing.JButton btngetIntnumber;
    private javax.swing.JButton btngetnumber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFilename;
    // End of variables declaration//GEN-END:variables
}
